flutter_icons:
  android: true
  ios: true
  image_path: assets/logo_foreground.png
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_foreground.png"
name: raheel
description: "Raheel - تطبيق مشاركة الرحلات"
publish_to: 'none'
version: 1.0.0+3


environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.2
  supabase_flutter: ^2.12.0
  http: ^1.6.0
  provider: ^6.1.5+1
  logger: ^2.6.2
  app_links: ^6.4.1
  connectivity_plus: any
  url_launcher: ^6.3.2
  crypto: ^3.0.7
  lottie: ^3.3.2
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
    - assets/lottie/earth_tag.json
    - assets/lottie/loadingcar.json
    - assets/lottie/carr.json
  fonts:
    - family: QTSHoby
      fonts:
        - asset: fonts/QTS-Hoby-OUT-LINE.otf
          weight: 400
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo.ttf
    - family: DahkaEmbossed
      fonts:
        - asset: assets/fonts/dahka-embossed.ttf
    - family: tam
      fonts:
        - asset: assets/fonts/tam.otf
    - family: lama
      fonts:
        - asset: assets/fonts/lama.otf
    - family: typokar
      fonts:
        - asset: assets/fonts/typokar.ttf
